### PR TITLE
Update tooling and dependencies. Fixes #789

### LINKED ISSUE #789: Update tooling and dependencies
The tooling and dependencies have atrophied and are out-of-date. This is causing Greenkeeper PRs to fail the build and as such I've just been deleting these PRs and branches without merging them which is why the dependencies are so out-of-date.

We need to update the tools and dependencies and get the build working again before working on new features. This should be too difficult a task.

### PR DESCRIPTION
**Pull request by mateusmarquezini**
CHANGELOG [#789](https://github.com/guyellis/learn/issues/789)
--

- Since webpack v4 the **extract-text-webpack-plugin** should not be used for css. It's deprecated. Plugin recommended according to its GitHub repository: **mini-css-extract-plugin**;
- Webpack updated, so, the webpack.loaders file structure has changed

**Updated libraries**:

- autoprefixer 9.5.1 > 9.6.1;
- extract-text-webpack-plugin (deprecated) > mini-css-extract-plugin 0.7.0
- fs-extra 7.0.1 > 8.1.0
- html-webpack-plugin 2.30.1 > 3.2.0
- lodash 4.17.11 > 4.17.12
- react-markdown 4.0.8 > 4.1.0
- react-router-dom 4.4.0 > 5.0.1
- webpack 3x > 4.35.3
- eslint 5.16.0 6.0.1
- eslint-config-airbnb 17.1.0 > 17.1.1
- eslint-config-airbnb-base 13.1.0 > 13.2.0
- eslint-plugin-import 2.17.2 > 2.18.0
- eslint-plugin-jest 22.6.2 > 22.7.2
- eslint-plugin-jsx-a11y 6.1.2 > 6.2.2
- eslint-plugin-react 7.12.4 > 7.14.1
- url-loade 1.1.2 > 2.0.1
- webpack-dev-server 2.x > ^3.1.4

**Added new libraries**:

- webpack-cli: ^3.1.1
- webpack-dev-server ^3.1.4

The application was tested in my local environment and everything seems works perfectly.
I couldn't test it in production mode, only dev.

_Any feedback, please feel free to reach me out._

### CODE REVIEW

**Comment by guyellis** [comment]
@mateusmarquezini - good work!

I just ran `npm run build` and I got this error:

```shell
/.../learn/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

I think that this is fairly easy to fix. I did this in another project and it's as simple as the error says: https://github.com/guyellis/plant/blob/5915836f6dc26e49ea9ca4179e7167543a4afd2c/webpack.config.js#L111-L113

**Comment by guyellis** [comment]
Something that I think I should have added to this project is `npm run build` as part of the `test` command in package.json which would then catch any breaking changes in webpack or its config. You can add that if you want or I can add it later.

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini - good work!
> 
> I just ran `npm run build` and I got this error:
> 
> ```shell
> /.../learn/node_modules/webpack-cli/bin/cli.js:93
> 				throw err;
> 				^
> 
> Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
> ```
> 
> I think that this is fairly easy to fix. I did this in another project and it's as simple as the error says: https://github.com/guyellis/plant/blob/5915836f6dc26e49ea9ca4179e7167543a4afd2c/webpack.config.js#L111-L113

Thanks! I'm going to fix this and add the build task while test task is executed as well.

**Comment by mateusmarquezini** [comment]
@guyellis Uglify plugin has been removed. Now, when I ran npm run build I got this error:

` ERROR in ./src/index.scss 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .blueBg {
    | 	background-color: red;
    | 	color: white;`

I was looking for use of this file "/src/index.scss"  into the project and I didn't found anything referencing it.
Also, removing it from webpack.production.config:

line 24:
`entry: [
    './src/index.jsx',
  ]`

the build task finished successfully.

I'd like to know. Is there any special use with this file? I really didn't find anything using it.

**Comment by guyellis** [comment]
@mateusmarquezini  - yes - I believe the index.scss file is referenced here: https://github.com/guyellis/learn/blob/74a6283719db45bde668cca04992af8a35976195/webpack.production.config.js#L17

And here is where the loader is specified: https://github.com/guyellis/learn/blob/74a6283719db45bde668cca04992af8a35976195/webpack.config.js#L14

**Comment by guyellis** [comment]
@mateusmarquezini 

> I'd like to know. Is there any special use with this file? I really didn't find anything using it.

That file is used to generate the CSS file for the project.

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini
> 
> > I'd like to know. Is there any special use with this file? I really didn't find anything using it.
> 
> That file is used to generate the CSS file for the project.

Thanks. I think I'm getting this error because the plugin **mini-css-extract-plugin** was added to the project.
I'll check better what is the real problem.

**Comment by mateusmarquezini** [comment]
Hi @guyellis 

Changes in the latest commit: 

- Uglify plugin removed successfully;
- Some Webpack settings was improved and fixed (e.g., css-loader);
- The command `npm run test` now runs the build task too.

Let me know what you think about this changes. Any feedback please contact me. Thx :smiley:

**Pull request merged**
