### PR TITLE
Switch from Babel to Typescript. Fixes #801

### LINKED ISSUE #801: Update dependencies
At 7/19/19 the outdated dependencies are:

```
Package                  Current   Wanted   Latest  Location
babel-eslint              10.0.1   10.0.1   10.0.2  learn
babel-jest                23.6.0   23.6.0   24.8.0  learn
babel-loader               7.1.5    7.1.5    8.0.6  learn
css-loader                 2.1.1    2.1.1    3.1.0  learn
eslint-plugin-jest       22.11.0  22.11.0  22.11.1  learn
eslint-plugin-jsx-a11y     6.2.2    6.2.2    6.2.3  learn
eslint-plugin-react       7.14.1   7.14.1   7.14.2  learn
jest                      23.6.0   23.6.0   24.8.0  learn
mini-css-extract-plugin    0.7.0    0.7.0    0.8.0  learn
moment                    2.22.2   2.22.2   2.24.0  learn
node-sass                 4.11.0   4.11.0   4.12.0  learn
prop-types                15.7.1   15.7.1   15.7.2  learn
webpack                   4.35.3   4.35.3   4.36.1  learn
webpack-dashboard          3.0.3    3.0.3    3.0.7  learn
```

These need to be updated. Some of these can be updated en masse and other will need to be done one-by-one. Issue for [css-loader is here](#802)

### PR DESCRIPTION
**Pull request by guyellis**

### CODE REVIEW

**Comment by guyellis** [comment]
Not sure why the Travis build is failing. Working okay locally for me.

@mateusmarquezini - can you try pulling this branch and doing an `npm i` and then `npm t` and see if it builds clean for you locally?

**Comment by mateusmarquezini** [comment]
@guyellis sure, I'm going to see what's happening with the build.

**Comment by guyellis** [comment]
@mateusmarquezini is it building and testing clean for you locally? I see this error on Travis but can't reproduce this locally. Can you see anything in the Travis file that would cause this?

```shell
FAIL dist/test/learn/math/drill/finished.test.js
  Finished
    ✕ should render when there is a single incorrect result (47ms)
    ✕ should render when there is a single correct result (17ms)
    ✕ should render when there is a mix of correct and incorrect results (12ms)
  ● Finished › should render when there is a single incorrect result
```

**Comment by mateusmarquezini** [comment]
@guyellis I can't reproduce it too. Locally everything works fine for me. I think this error should be something about CI config. I'll study that as soon as possible.

**Comment by guyellis** [comment]
@mateusmarquezini - I just locked all dependencies down to an exact version and fixed the merge conflict to see if that would change things...

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini - I just locked all dependencies down to an exact version and fixed the merge conflict to see if that would change things...

@guyellis I think the problem is related to jest settings in jest.config.js.

I was following this thread yesterday https://github.com/facebook/jest/issues/7094#issuecomment-503823627 but it still not working.

**Comment by guyellis** [comment]
@mateusmarquezini - you were on the right path - awesome work! We just needed to relax the exclusion on that path. You solved it!

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini - you were on the right path - awesome work! We just needed to relax the exclusion on that path. You solved it!

@guyellis haha thanks! We solved it. Good work!

**Pull request merged**
